name: sporty

services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sporty
    ports:
      - "5432:5432"
    volumes:
      - sporty_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d sporty"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

volumes:
  sporty_postgres_data:
